# This is a GitHub Action workflow that will automatically build and minify the editor.
# It runs every time you push changes to the 'main' branch.

name: Build and Minify Editor

on:
  push:
    branches: [ "main" ] # Triggers the workflow on push events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The type of virtual machine to run the job on

    # Grant permissions for the action to write to the repository
    permissions:
      contents: write

    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run the build commands using esbuild
      - name: Build and Minify JavaScript
        run: npx esbuild src/editor.js --bundle --minify --outfile=dist/editor.min.js

      - name: Build and Minify CSS
        run: npx esbuild src/editor.css --minify --outfile=dist/editor.min.css

      # Step 3: Copy language files to dist
      - name: Copy language files
        run: |
          mkdir -p dist/lang
          cp src/lang/*.json dist/lang/

      # Step 4: Commit the new 'dist' files back to the repository
      - name: Commit and Push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: Update dist folder with minified assets and languages"
          file_pattern: dist/ # Commit any changes within the dist directory
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"